
document.addEventListener('DOMContentLoaded',async()=>{
 const old=document.querySelector('header.navbar');
 const header=document.createElement('header');header.className='navbar';header.id='senyaHeader';header.innerHTML='<div class="navbar-container"><a class="logo" href="index.html"><img src="img/Senyalogo.png" alt="SENYA"></a><nav id="senyaNavigation" aria-label="Main navigation"><ul class="nav-links"></ul></nav><div class="right-actions"><button class="menu-toggle" aria-label="Menu" aria-expanded="false" aria-controls="senyaNavigation"><span aria-hidden="true">☰</span></button></div></div>';
 if(old)old.replaceWith(header);else document.body.prepend(header);
 const nav=header.querySelector('.nav-links');const menuButton=header.querySelector('.menu-toggle');menuButton.setAttribute('aria-controls','senyaSignMenu');
 let role=null;try{if(sessionStorage.getItem('senyaAuth')){const [p]=await Senya.select('profiles');role=p?.role;}}catch(e){Senya.error(e);}
 const path=location.pathname.split('/').pop()||'index.html';
 const entries=role==='interpreter'?[['My appointments','interpreter-dashboard.html'],['My profile','profile.html'],['Support','soporte.html']]:role==='user'?[['My appointments','appointments.html'],['Request assistance','request.html'],['My profile','profile.html'],['Support','soporte.html']]:role==='admin'?[['Applications','admin.html'],['My profile','profile.html']]:[['Home','index.html'],['Partner network','opciones.html'],['About us','about.html'],['Contact','soporte.html'],['Sign in','signin.html']];
 for(const [label,href] of entries){const a=document.createElement('a');a.textContent=label;a.href=href;if(path===href||(href==='profile.html'&&path==='interpreter-profile.html')){a.setAttribute('aria-current','page');a.classList.add('active');}const li=document.createElement('li');li.append(a);nav.append(li);}
 if(document.getElementById('accessibilityPanel')){const b=document.createElement('button');b.textContent='Accessibility';b.id='accessibilityBtn';b.className='help-btn';b.onclick=()=>{document.getElementById('accessibilityPanel').classList.toggle('open');};header.querySelector('.right-actions').prepend(b);}
 const panel=document.createElement('div');panel.id='senyaSignMenu';panel.className='sign-language-panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Navigation');panel.innerHTML='<div class="sign-panel-header"><h2>Explore SENYA</h2><button class="sign-close-btn" aria-label="Close menu">×</button></div><div class="sign-panel-content"></div>';
 const videos={'index.html':'home','opciones.html':'network','profile.html':'perfil','about.html':'about','soporte.html':'contacto'};
 for(const [label,href] of entries){const a=document.createElement('a');a.className='sign-video-card';a.href=href;const videoName=videos[href];if(videoName){const video=document.createElement('video');video.muted=true;video.loop=true;video.playsInline=true;video.preload='metadata';video.src='videos/'+videoName+'.mp4';a.append(video);}const text=document.createElement('span');text.textContent=label;a.append(text);panel.querySelector('.sign-panel-content').append(a);}
 document.body.append(panel);const close=()=>{panel.hidden=true;panel.classList.remove('open');document.body.classList.remove('sign-menu-open');menuButton.setAttribute('aria-expanded','false');panel.querySelectorAll('video').forEach(v=>v.pause());menuButton.focus();};menuButton.onclick=()=>{panel.hidden=false;panel.classList.add('open');document.body.classList.add('sign-menu-open');menuButton.setAttribute('aria-expanded','true');panel.querySelectorAll('video').forEach(v=>v.play().catch(()=>{}));panel.querySelector('button').focus();};panel.querySelector('button').onclick=close;panel.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=[...panel.querySelectorAll('button,a')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 if(role){const b=document.createElement('button');b.textContent='Log out';b.onclick=()=>Senya.signout();const li=document.createElement('li');li.append(b);nav.append(li);}
});
