document.addEventListener('DOMContentLoaded',async()=>{
 const list=document.getElementById('applications'),status=document.getElementById('adminStatus'),filter=document.getElementById('filter');let rows=[],busy=false;
 const node=(tag,text)=>{const el=document.createElement(tag);if(text)el.textContent=text;return el;};
 const theme=()=>document.body.classList.toggle('light-theme',localStorage.getItem('theme')==='light');theme();document.getElementById('theme').onclick=()=>{localStorage.setItem('theme',document.body.classList.contains('light-theme')?'dark':'light');theme();};document.getElementById('logout').onclick=()=>Senya.signout();
 async function load(){status.textContent='Loading applications…';try{rows=await Senya.rpc('admin_applications');render();status.textContent=rows.filter(r=>r.verification_status==='pending').length+' pending applications';}catch(e){status.textContent=e.message;}}
 function render(){list.replaceChildren();const shown=rows.filter(r=>filter.value==='all'||r.verification_status===filter.value);if(!shown.length){list.append(node('p','No applications in this category.'));return;}
 for(const r of shown){const card=node('article');card.className='card';card.append(node('h2',r.first_name+' '+r.last_name),node('p','Status: '+r.verification_status),node('p','Languages: '+r.languages.join(', ')),node('p','Specialties: '+r.specialties.join(', ')),node('p','Experience: '+r.experience+' years'),node('p','Phone: '+r.phone),node('p','Certification: '+r.certification),node('p',r.bio));
 const certificates=node('div');certificates.className='actions';
 for(const [index,path] of r.certificates.entries()){const button=node('button','Open certificate '+(index+1));button.onclick=async()=>{button.disabled=true;try{const c=await Senya.settings();const response=await fetch(c.url+'/storage/v1/object/authenticated/certificates/'+path.split('/').map(encodeURIComponent).join('/'),{headers:{apikey:c.key,Authorization:'Bearer '+await Senya.token()}});if(!response.ok)throw Error('Unable to open this certificate.');const blob=await response.blob();if(!['application/pdf','image/png','image/jpeg'].includes(blob.type))throw Error('Unsupported certificate format.');const url=URL.createObjectURL(blob);const link=node('a','View certificate '+(index+1));link.href=url;link.target='_blank';link.rel='noopener noreferrer';button.replaceWith(link);addEventListener('pagehide',()=>URL.revokeObjectURL(url),{once:true});status.textContent='Certificate ready. Select View certificate to open it.';}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};certificates.append(button);}
 card.append(certificates);if(!r.certificates.length)card.append(node('p','No certificate uploaded. Approval is unavailable.'));
 if(r.verification_status==='pending'){
 const label=node('label','Review note (required for rejection)'),note=node('textarea');note.maxLength=2000;label.append(note);card.append(label);
 const reviewed=node('input');reviewed.type='checkbox';const reviewLabel=node('label');reviewLabel.append(reviewed,document.createTextNode(' I have reviewed the profile and certificate.'));card.append(reviewLabel);
 const actions=node('div');actions.className='actions';
 for(const decision of ['verified','rejected']){const b=node('button',decision==='verified'?'Approve interpreter':'Reject application');if(decision==='verified'){b.className='primary';b.disabled=true;reviewed.onchange=()=>b.disabled=!reviewed.checked||!r.certificates.length;}
 b.onclick=async()=>{if(busy)return;if(decision==='rejected'&&!note.value.trim()){note.focus();status.textContent='Enter a reason for rejection.';return;}busy=true;b.disabled=true;try{await Senya.rpc('review_interpreter',{p_id:r.id,p_decision:decision,p_note:note.value});await load();status.textContent=decision==='verified'?'Interpreter approved. They can now enable availability.':'Application rejected.';}catch(e){status.textContent=e.message;b.disabled=decision==='verified'&&(!reviewed.checked||!r.certificates.length);}finally{busy=false;}};actions.append(b);}card.append(actions);
 }else for(const review of r.reviews)card.append(node('p',new Date(review.created_at).toLocaleString()+' · '+review.decision+(review.note?' · '+review.note:'')));
 list.append(card);}}
 filter.onchange=render;document.getElementById('refresh').onclick=()=>{if(!busy)load();};
 try{await Senya.me('admin');await load();}catch(e){status.textContent=e.message;}
});
